// Copyright 2026 Cognitive Substrate Project. Apache-2.0 License.
//! Grant operation: kernel-initiated capability creation.
//!
//! This module implements the grant_capability function, which is the only way
//! to create a new unforgeable capability in the system.
//! See Engineering Plan § 3.1.0 & § 3.2.3: Grant Operations.

use alloc::string::String;
use core::fmt::{self, Debug, Display};

use crate::capability::Capability;
use crate::capability_table::{CapabilityEntry, CapabilityTable, PageMapping, PagePermission};
use crate::chain::ChainEntry;
use crate::constraints::{CapConstraints, Timestamp};
use crate::error::CapError;
use crate::ids::{AgentID, CapID, ResourceID, ResourceType};
use crate::mandatory_policy::MandatoryCapabilityPolicy;
use crate::operations::OperationSet;
use crate::policy_engine::{EvalContext, MandatoryPolicyEngine, PolicyEvaluator};

/// A record of a grant operation, used for audit trails.
///
/// See Engineering Plan § 3.2.3: Grant Operations.
#[derive(Clone, Debug)]
pub struct GrantAuditRecord {
    /// The ID of the granted capability.
    pub cap_id: CapID,

    /// The agent who received the grant.
    pub target_agent: AgentID,

    /// The resource reference (type and ID) being granted.
    pub resource_type: ResourceType,
    pub resource_id: ResourceID,

    /// The operations granted by this capability.
    pub operations: OperationSet,

    /// Constraints applied to the capability.
    pub constraints: CapConstraints,

    /// Timestamp when the grant occurred.
    pub timestamp: Timestamp,

    /// Whether all mandatory policies were satisfied.
    pub policy_checks_passed: bool,
}

impl Display for GrantAuditRecord {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "Grant({} -> {} on {}:{}, ops={}, policy_ok={})",
            self.cap_id,
            self.target_agent,
            self.resource_type,
            self.resource_id,
            self.operations.bits(),
            self.policy_checks_passed
        )
    }
}

/// Grants a new capability to an agent for a resource.
///
/// This is the kernel-only operation that creates unforgeable capabilities.
/// Per Engineering Plan § 3.1.3, CapIDs are generated by the kernel with
/// cryptographic randomness and cannot be forged by user code.
///
/// The operation is atomic: either fully succeeds or fully fails.
/// Before granting, ALL MandatoryCapabilityPolicies are validated.
///
/// # Arguments
/// * `table` - The capability table where the new capability will be stored
/// * `cap_id` - The kernel-assigned capability ID (must be unique)
/// * `target_agent` - The agent receiving the capability
/// * `resource_type` - The type of resource being granted
/// * `resource_id` - The specific resource ID
/// * `operations` - The set of operations granted
/// * `constraints` - Additional constraints (time bounds, rate limits, etc.)
/// * `policy_engine` - The mandatory policy enforcement engine
/// * `now` - Current timestamp
///
/// # Latency Target
/// <500ns warm cache (per Engineering Plan § 3.2.3)
///
/// See Engineering Plan § 3.1.0 & § 3.2.3: Grant Operations.
pub fn grant_capability(
    table: &mut CapabilityTable,
    cap_id: CapID,
    target_agent: AgentID,
    resource_type: ResourceType,
    resource_id: ResourceID,
    operations: OperationSet,
    constraints: CapConstraints,
    policy_engine: &dyn PolicyEvaluator,
    now: Timestamp,
) -> Result<(CapID, GrantAuditRecord), CapError> {
    // Step 1: Create the capability object (not yet inserted)
    let mut capability = Capability::new(
        cap_id.clone(),
        target_agent.clone(),
        resource_type.clone(),
        resource_id.clone(),
        operations,
        now,
    );
    capability.constraints = constraints.clone();

    // Step 2: Validate against all mandatory policies
    let eval_context = EvalContext::new(
        now.nanos(),
        AgentID::new("kernel"),
        target_agent.clone(),
        "grant",
    );
    let decision = policy_engine.evaluate(&capability, &eval_context);

    if decision.denies_operation() {
        return Err(CapError::PolicyDenied(format!(
            "grant operation denied by policy: {}",
            decision
        )));
    }

    let policy_checks_passed = decision.allows_operation();

    // Step 3: Add initial chain entry (root grant, no parent)
    let root_entry = ChainEntry::new(
        AgentID::new("kernel"),
        target_agent.clone(),
        CapConstraints::new(),
        now,
    );
    capability.chain.add_entry(root_entry)?;

    // Step 4: Create capability table entry
    let entry = CapabilityEntry::new(capability.clone(), target_agent.clone(), now);

    // Step 5: Insert into capability table (atomic point)
    table.insert(cap_id.clone(), entry)?;

    // Step 6: Create and return audit record
    let audit_record = GrantAuditRecord {
        cap_id: cap_id.clone(),
        target_agent,
        resource_type,
        resource_id,
        operations,
        constraints,
        timestamp: now,
        policy_checks_passed,
    };

    Ok((cap_id, audit_record))
}

/// Grants a capability with an optional page table mapping.
///
/// This variant of grant_capability also sets up page table mappings for
/// resources that require memory access control.
///
/// See Engineering Plan § 3.2.3: Grant Operations.
pub fn grant_capability_with_mapping(
    table: &mut CapabilityTable,
    cap_id: CapID,
    target_agent: AgentID,
    resource_type: ResourceType,
    resource_id: ResourceID,
    operations: OperationSet,
    constraints: CapConstraints,
    page_mapping: Option<PageMapping>,
    policy_engine: &dyn PolicyEvaluator,
    now: Timestamp,
) -> Result<(CapID, GrantAuditRecord), CapError> {
    // First, grant the capability normally
    let (granted_cap_id, audit_record) = grant_capability(
        table,
        cap_id.clone(),
        target_agent,
        resource_type,
        resource_id,
        operations,
        constraints,
        policy_engine,
        now,
    )?;

    // Then, if a mapping is provided, add it to the entry
    if let Some(mapping) = page_mapping {
        let entry = table.lookup_mut(&granted_cap_id)?;
        entry.add_page_mapping(mapping);
    }

    Ok((granted_cap_id, audit_record))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::mandatory_policy::PredicateComposition;
    use crate::policy::BasicPolicyEngine;
use alloc::format;
use alloc::string::ToString;

    fn make_basic_policy_engine() -> BasicPolicyEngine {
        BasicPolicyEngine::new()
    }

    fn make_mandatory_engine() -> crate::policy_engine::MandatoryPolicyEngine {
        crate::policy_engine::MandatoryPolicyEngine::new()
    }

    #[test]
    fn test_grant_basic_capability() {
        let mut table = CapabilityTable::new();
        let policy_engine = make_basic_policy_engine();
        let now = Timestamp::new(1000);

        let cap_id = CapID::from_bytes([1u8; 32]);
        let agent = AgentID::new("test-agent");
        let resource_type = ResourceType::file();
        let resource_id = ResourceID::new("test-file");

        let (granted_id, audit) = grant_capability(
            &mut table,
            cap_id.clone(),
            agent.clone(),
            resource_type,
            resource_id,
            OperationSet::all(),
            CapConstraints::new(),
            &policy_engine,
            now,
        )
        .unwrap();

        assert_eq!(granted_id, cap_id);
        assert_eq!(audit.target_agent, agent);
        assert_eq!(audit.timestamp, now);
        assert!(audit.policy_checks_passed);
        assert_eq!(table.len(), 1);
    }

    #[test]
    fn test_grant_with_constraints() {
        let mut table = CapabilityTable::new();
        let policy_engine = make_basic_policy_engine();
        let now = Timestamp::new(1000);

        let cap_id = CapID::from_bytes([2u8; 32]);
        let agent = AgentID::new("test-agent");
        let mut constraints = CapConstraints::new();
        constraints.time_bound = Some(crate::constraints::TimeBound::new(
            Timestamp::new(1000),
            Timestamp::new(2000),
        ));

        let (_, audit) = grant_capability(
            &mut table,
            cap_id,
            agent,
            ResourceType::file(),
            ResourceID::new("test-file"),
            OperationSet::read(),
            constraints,
            &policy_engine,
            now,
        )
        .unwrap();

        assert!(audit.constraints.time_bound.is_some());
    }

    #[test]
    fn test_grant_duplicate_cap_id_fails() {
        let mut table = CapabilityTable::new();
        let policy_engine = make_basic_policy_engine();
        let now = Timestamp::new(1000);

        let cap_id = CapID::from_bytes([3u8; 32]);
        let agent = AgentID::new("test-agent");

        // First grant succeeds
        grant_capability(
            &mut table,
            cap_id.clone(),
            agent.clone(),
            ResourceType::file(),
            ResourceID::new("file-1"),
            OperationSet::all(),
            CapConstraints::new(),
            &policy_engine,
            now,
        )
        .unwrap();

        // Second grant with same ID fails
        let result = grant_capability(
            &mut table,
            cap_id,
            agent,
            ResourceType::file(),
            ResourceID::new("file-2"),
            OperationSet::all(),
            CapConstraints::new(),
            &policy_engine,
            now,
        );

        assert!(result.is_err());
    }

    #[test]
    fn test_grant_capability_appears_in_table() {
        let mut table = CapabilityTable::new();
        let policy_engine = make_basic_policy_engine();
        let now = Timestamp::new(1000);

        let cap_id = CapID::from_bytes([4u8; 32]);
        let agent = AgentID::new("test-agent");

        grant_capability(
            &mut table,
            cap_id.clone(),
            agent.clone(),
            ResourceType::file(),
            ResourceID::new("test-file"),
            OperationSet::all(),
            CapConstraints::new(),
            &policy_engine,
            now,
        )
        .unwrap();

        let entry = table.lookup(&cap_id).unwrap();
        assert!(entry.is_held_by(&agent));
    }

    #[test]
    fn test_grant_creates_audit_record_with_correct_fields() {
        let mut table = CapabilityTable::new();
        let policy_engine = make_basic_policy_engine();
        let now = Timestamp::new(1000);

        let cap_id = CapID::from_bytes([5u8; 32]);
        let agent = AgentID::new("test-agent");
        let resource_type = ResourceType::memory();
        let resource_id = ResourceID::new("mem-region");

        let (_, audit) = grant_capability(
            &mut table,
            cap_id.clone(),
            agent.clone(),
            resource_type.clone(),
            resource_id.clone(),
            OperationSet::write(),
            CapConstraints::new(),
            &policy_engine,
            now,
        )
        .unwrap();

        assert_eq!(audit.cap_id, cap_id);
        assert_eq!(audit.target_agent, agent);
        assert_eq!(audit.resource_type, resource_type);
        assert_eq!(audit.resource_id, resource_id);
        assert_eq!(audit.operations, OperationSet::write());
        assert_eq!(audit.timestamp, now);
    }

    #[test]
    fn test_grant_with_page_mapping() {
        let mut table = CapabilityTable::new();
        let policy_engine = make_basic_policy_engine();
        let now = Timestamp::new(1000);

        let cap_id = CapID::from_bytes([6u8; 32]);
        let agent = AgentID::new("test-agent");
        let mapping = PageMapping::new(0x1000, 0x2000, 0x1000, PagePermission::ReadWrite);

        let (granted_id, _) = grant_capability_with_mapping(
            &mut table,
            cap_id.clone(),
            agent,
            ResourceType::memory(),
            ResourceID::new("mem-region"),
            OperationSet::all(),
            CapConstraints::new(),
            Some(mapping),
            &policy_engine,
            now,
        )
        .unwrap();

        let entry = table.lookup(&granted_id).unwrap();
        assert_eq!(entry.page_table_mappings.len(), 1);
        assert_eq!(entry.page_table_mappings[0].virtual_addr, 0x1000);
    }

    #[test]
    fn test_grant_with_mandatory_policy_acceptance() {
        let mut table = CapabilityTable::new();
        let policy_engine = make_mandatory_engine();
        let now = Timestamp::new(1000);

        let cap_id = CapID::from_bytes([7u8; 32]);
        let agent = AgentID::new("test-agent");

        let (_, audit) = grant_capability(
            &mut table,
            cap_id,
            agent,
            ResourceType::file(),
            ResourceID::new("test-file"),
            OperationSet::read(),
            CapConstraints::new(),
            &policy_engine,
            now,
        )
        .unwrap();

        assert!(audit.policy_checks_passed);
    }

    #[test]
    fn test_grant_audit_record_display() {
        let cap_id = CapID::from_bytes([8u8; 32]);
        let agent = AgentID::new("test-agent");
        let audit = GrantAuditRecord {
            cap_id,
            target_agent: agent,
            resource_type: ResourceType::file(),
            resource_id: ResourceID::new("test-file"),
            operations: OperationSet::all(),
            constraints: CapConstraints::new(),
            timestamp: Timestamp::new(1000),
            policy_checks_passed: true,
        };

        let display = audit.to_string();
        assert!(display.contains("Grant"));
        assert!(display.contains("test-agent"));
    }

    #[test]
    fn test_grant_created_capability_has_root_chain_entry() {
        let mut table = CapabilityTable::new();
        let policy_engine = make_basic_policy_engine();
        let now = Timestamp::new(1000);

        let cap_id = CapID::from_bytes([9u8; 32]);
        let agent = AgentID::new("test-agent");

        grant_capability(
            &mut table,
            cap_id.clone(),
            agent.clone(),
            ResourceType::file(),
            ResourceID::new("test-file"),
            OperationSet::all(),
            CapConstraints::new(),
            &policy_engine,
            now,
        )
        .unwrap();

        let entry = table.lookup(&cap_id).unwrap();
        assert!(entry.capability.chain.len() > 0);
    }

    #[test]
    fn test_grant_with_multiple_agents() {
        let mut table = CapabilityTable::new();
        let policy_engine = make_basic_policy_engine();
        let now = Timestamp::new(1000);

        let cap_id_1 = CapID::from_bytes([10u8; 32]);
        let cap_id_2 = CapID::from_bytes([11u8; 32]);
        let agent_1 = AgentID::new("agent-1");
        let agent_2 = AgentID::new("agent-2");

        grant_capability(
            &mut table,
            cap_id_1.clone(),
            agent_1.clone(),
            ResourceType::file(),
            ResourceID::new("file-1"),
            OperationSet::all(),
            CapConstraints::new(),
            &policy_engine,
            now,
        )
        .unwrap();

        grant_capability(
            &mut table,
            cap_id_2.clone(),
            agent_2.clone(),
            ResourceType::file(),
            ResourceID::new("file-2"),
            OperationSet::all(),
            CapConstraints::new(),
            &policy_engine,
            now,
        )
        .unwrap();

        let entry_1 = table.lookup(&cap_id_1).unwrap();
        let entry_2 = table.lookup(&cap_id_2).unwrap();

        assert!(entry_1.is_held_by(&agent_1));
        assert!(entry_2.is_held_by(&agent_2));
        assert!(!entry_1.is_held_by(&agent_2));
        assert!(!entry_2.is_held_by(&agent_1));
    }

    #[test]
    fn test_grant_different_resource_types() {
        let mut table = CapabilityTable::new();
        let policy_engine = make_basic_policy_engine();
        let now = Timestamp::new(1000);

        let file_cap_id = CapID::from_bytes([12u8; 32]);
        let mem_cap_id = CapID::from_bytes([13u8; 32]);
        let agent = AgentID::new("test-agent");

        grant_capability(
            &mut table,
            file_cap_id.clone(),
            agent.clone(),
            ResourceType::file(),
            ResourceID::new("test-file"),
            OperationSet::all(),
            CapConstraints::new(),
            &policy_engine,
            now,
        )
        .unwrap();

        grant_capability(
            &mut table,
            mem_cap_id.clone(),
            agent.clone(),
            ResourceType::memory(),
            ResourceID::new("test-memory"),
            OperationSet::all(),
            CapConstraints::new(),
            &policy_engine,
            now,
        )
        .unwrap();

        let file_entry = table.lookup(&file_cap_id).unwrap();
        let mem_entry = table.lookup(&mem_cap_id).unwrap();

        assert_eq!(
            file_entry.capability.target_resource_type,
            ResourceType::file()
        );
        assert_eq!(
            mem_entry.capability.target_resource_type,
            ResourceType::memory()
        );
    }

    #[test]
    fn test_grant_with_multiple_page_mappings() {
        let mut table = CapabilityTable::new();
        let policy_engine = make_basic_policy_engine();
        let now = Timestamp::new(1000);

        let cap_id = CapID::from_bytes([14u8; 32]);
        let agent = AgentID::new("test-agent");
        let mapping1 = PageMapping::new(0x1000, 0x2000, 0x1000, PagePermission::ReadWrite);

        let (granted_id, _) = grant_capability_with_mapping(
            &mut table,
            cap_id.clone(),
            agent,
            ResourceType::memory(),
            ResourceID::new("mem-region"),
            OperationSet::all(),
            CapConstraints::new(),
            Some(mapping1),
            &policy_engine,
            now,
        )
        .unwrap();

        let mut entry = table.lookup_mut(&granted_id).unwrap();
        let mapping2 = PageMapping::new(0x3000, 0x4000, 0x1000, PagePermission::ReadOnly);
        entry.add_page_mapping(mapping2);

        let entry = table.lookup(&granted_id).unwrap();
        assert_eq!(entry.page_table_mappings.len(), 2);
    }

    #[test]
    fn test_grant_preserves_capability_id() {
        let mut table = CapabilityTable::new();
        let policy_engine = make_basic_policy_engine();
        let now = Timestamp::new(1000);

        let cap_id = CapID::from_bytes([15u8; 32]);
        let agent = AgentID::new("test-agent");

        let (returned_id, _) = grant_capability(
            &mut table,
            cap_id.clone(),
            agent,
            ResourceType::file(),
            ResourceID::new("test-file"),
            OperationSet::all(),
            CapConstraints::new(),
            &policy_engine,
            now,
        )
        .unwrap();

        assert_eq!(returned_id, cap_id);

        let entry = table.lookup(&cap_id).unwrap();
        assert_eq!(entry.capability.id, cap_id);
    }
}
