// Copyright 2026 Cognitive Substrate Project. Apache-2.0 License.
//! Strongly typed identifiers for capabilities, agents, and resources.
//!
//! All identifiers in the Cognitive Substrate are typed to prevent accidental confusion
//! and enable compile-time verification.
//! See Engineering Plan § 3.1.0: Core Domain Model & § 3.1.3: Unforgeable Identity.

use alloc::fmt;
use alloc::string::{String, ToString};
use core::fmt::{Debug, Display};
use core::hash::{Hash, Hasher};

/// A 256-bit unforgeable capability identifier, kernel-assigned.
///
/// See Engineering Plan § 3.1.3: Unforgeable Identity & Kernel Assignment.
/// CapIDs are:
/// - Generated by the kernel with cryptographic randomness (never by agents)
/// - Globally unique across all time and instances
/// - Immutable and non-transferable
/// - Used as the primary key for capability revocation & tracking
#[derive(Clone, PartialEq, Eq)]
pub struct CapID([u8; 32]);

impl CapID {
    /// Creates a new CapID from a 32-byte array.
    ///
    /// # Safety
    /// This is called only by the kernel during capability creation.
    /// User code should not construct CapIDs.
    pub const fn from_bytes(bytes: [u8; 32]) -> Self {
        CapID(bytes)
    }

    /// Returns the underlying 32-byte array.
    pub const fn as_bytes(&self) -> &[u8; 32] {
        &self.0
    }

    /// Exposes the capability ID as a reference to the byte slice.
    pub fn as_slice(&self) -> &[u8] {
        &self.0
    }
}

impl Debug for CapID {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_tuple("CapID")
            .field(&hex_encode(&self.0[..8]))
            .finish()
    }
}

impl Display for CapID {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "CapID({})", hex_encode(&self.0))
    }
}

impl Hash for CapID {
    fn hash<H: Hasher>(&self, state: &mut H) {
        self.0.hash(state);
    }
}

/// A strongly-typed agent identifier.
///
/// See Engineering Plan § 3.1.0: Core Domain Model.
/// Agents are principals (users, services, processes) that hold and exercise capabilities.
#[derive(Clone, PartialEq, Eq, Hash, Debug)]
pub struct AgentID(String);

impl AgentID {
    /// Creates a new agent ID from a string.
    pub fn new(id: impl Into<String>) -> Self {
        AgentID(id.into())
    }

    /// Returns a reference to the underlying string.
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl Display for AgentID {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "Agent({})", self.0)
    }
}

/// A strongly-typed resource identifier.
///
/// See Engineering Plan § 3.1.0: Core Domain Model.
/// Resources are the objects being protected by capabilities (files, memory regions, services, etc.).
#[derive(Clone, PartialEq, Eq, Hash, Debug)]
pub struct ResourceID(String);

impl ResourceID {
    /// Creates a new resource ID from a string.
    pub fn new(id: impl Into<String>) -> Self {
        ResourceID(id.into())
    }

    /// Returns a reference to the underlying string.
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl Display for ResourceID {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "Resource({})", self.0)
    }
}

/// A type tag for resources, enabling type-safe resource references.
///
/// See Engineering Plan § 3.1.0: Core Domain Model.
/// ResourceType ensures capabilities can only be used with compatible resource types.
#[derive(Clone, PartialEq, Eq, Hash, Debug)]
pub struct ResourceType(String);

impl ResourceType {
    /// Creates a new resource type from a string.
    pub fn new(type_name: impl Into<String>) -> Self {
        ResourceType(type_name.into())
    }

    /// Returns a reference to the underlying string.
    pub fn as_str(&self) -> &str {
        &self.0
    }

    /// Predefined type for file system resources.
    pub fn file() -> Self {
        ResourceType("file".to_string())
    }

    /// Predefined type for memory regions.
    pub fn memory() -> Self {
        ResourceType("memory".to_string())
    }

    /// Predefined type for service endpoints.
    pub fn service() -> Self {
        ResourceType("service".to_string())
    }
}

impl Display for ResourceType {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.0)
    }
}

/// A policy identifier for mandatory capability policies.
///
/// See Engineering Plan § 3.1.4: Mandatory & Stateless.
#[derive(Clone, PartialEq, Eq, Hash, Debug)]
pub struct PolicyID(String);

impl PolicyID {
    /// Creates a new policy ID.
    pub fn new(id: impl Into<String>) -> Self {
        PolicyID(id.into())
    }

    /// Returns a reference to the underlying string.
    pub fn as_str(&self) -> &str {
        &self.0
    }
}

impl Display for PolicyID {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "Policy({})", self.0)
    }
}

/// Encodes bytes as hex without allocation.
fn hex_encode(bytes: &[u8]) -> String {
    let mut result = String::new();
    for byte in bytes.iter().take(16) {
        // Use a simple hex encoding: just show first 16 bytes
        result.push_str(&format!("{:02x}", byte));
    }
    result
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_cap_id_creation() {
        let bytes = [42u8; 32];
        let cap_id = CapID::from_bytes(bytes);
        assert_eq!(cap_id.as_bytes(), &bytes);
    }

    #[test]
    fn test_cap_id_display() {
        let bytes = [0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d, 0x0e, 0x0f, 0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, 0x18, 0x19, 0x1a, 0x1b, 0x1c, 0x1d, 0x1e, 0x1f];
        let cap_id = CapID::from_bytes(bytes);
        let display = cap_id.to_string();
        assert!(display.contains("CapID"));
    }

    #[test]
    fn test_cap_id_debug() {
        let bytes = [42u8; 32];
        let cap_id = CapID::from_bytes(bytes);
        let debug_str = format!("{:?}", cap_id);
        assert!(debug_str.contains("CapID"));
    }

    #[test]
    fn test_cap_id_equality() {
        let bytes1 = [42u8; 32];
        let bytes2 = [43u8; 32];
        let cap_id1 = CapID::from_bytes(bytes1);
        let cap_id2 = CapID::from_bytes(bytes1);
        let cap_id3 = CapID::from_bytes(bytes2);

        assert_eq!(cap_id1, cap_id2);
        assert_ne!(cap_id1, cap_id3);
    }

    #[test]
    fn test_cap_id_hash() {
        use core::collections::hash_map::DefaultHasher;
use alloc::format;
use alloc::string::String;
use alloc::string::ToString;

        let bytes = [42u8; 32];
        let cap_id1 = CapID::from_bytes(bytes);
        let cap_id2 = CapID::from_bytes(bytes);

        let mut h1 = DefaultHasher::new();
        cap_id1.hash(&mut h1);
        let hash1 = h1.finish();

        let mut h2 = DefaultHasher::new();
        cap_id2.hash(&mut h2);
        let hash2 = h2.finish();

        assert_eq!(hash1, hash2);
    }

    #[test]
    fn test_agent_id_creation() {
        let agent = AgentID::new("agent-001");
        assert_eq!(agent.as_str(), "agent-001");
    }

    #[test]
    fn test_agent_id_display() {
        let agent = AgentID::new("system");
        assert_eq!(agent.to_string(), "Agent(system)");
    }

    #[test]
    fn test_resource_id_creation() {
        let resource = ResourceID::new("file:/etc/passwd");
        assert_eq!(resource.as_str(), "file:/etc/passwd");
    }

    #[test]
    fn test_resource_type_predefined() {
        assert_eq!(ResourceType::file().as_str(), "file");
        assert_eq!(ResourceType::memory().as_str(), "memory");
        assert_eq!(ResourceType::service().as_str(), "service");
    }

    #[test]
    fn test_policy_id_creation() {
        let policy = PolicyID::new("mandatory-isolation");
        assert_eq!(policy.as_str(), "mandatory-isolation");
    }

    #[test]
    fn test_ids_are_distinct_types() {
        let agent = AgentID::new("a");
        let resource = ResourceID::new("a");
        // These have different types, so they can't be confused at compile time
        assert_eq!(agent.as_str(), resource.as_str());
    }
}
